### ISSUE TITLE
Unable to get Zapier to authenticate

### ISSUE THREAD

**Issue by xlilcasper** [sammachin/node-red-contrib-zapier#1]
I currently have node red exposed at https://nodered.hassio.mydomain.com I have tested that I can hit that end point outside my local network. It is setup with port 80 forwarded to my hassio server via an ngnix proxy (192.168.0.5:80 -> 192.168.0.90:1880). I then tested that I could hit an http in end point. I am able to hit and trigger that flow at https://nodered.hassio.mydomain.com/endpoint/hello . When I go to allow Zapier to access my Node-RED account I put in the token I generated from the Zapier action node (that is connected just to a debug ndoe.) and the url https://nodered.hassio.mydomain.com and hit Yes, continue. This results in an error of authentication failed: The token you supplied is invalid.

HA: 0.118.3 - Docker version
Node Red: 7.2.11 - Installed by the supervisor

**Comment by sammachin** [comment]
Sorry missed this issue!

If you're using https urls then you'll need port 443 port 80 is for http

You'll also need an SSL cert for your server if using https
